[[redirects]]
from = "https://gamedevelop.netlify.app/"
to = "https://gamedevelop.io/"
status = 301
force = true

[[redirects]]
from = "/index.html"
to = "/"
status = 301
force = true

[[redirects]]
from = "/resources.html"
to = "/resources"
status = 301
force = true

[[redirects]]
from = "/suggestion.html"
to = "/suggestion"
status = 301
force = true

[[redirects]]
from = "/about.html"
to = "/about"
status = 301
force = true

[[redirects]]
from = "/404.html"
to = "/404"
status = 301
force = true

[[redirects]]
from = "/guides.html"
to = "/guides"
status = 301
force = true

[[redirects]]
from = "/guides/introductory.html"
to = "/guides/introductory"
status = 301
force = true

[[redirects]]
from = "/guides/introductory/concept.html"
to = "/guides/introductory/concept"
status = 301
force = true

[[redirects]]
from = "/guides/introductory/business.html"
to = "/guides/introductory/business"
status = 301
force = true

[[redirects]]
from = "/guides/introductory/production.html"
to = "/guides/introductory/production"
status = 301
force = true

[[redirects]]
from = "/guides/industry.html"
to = "/guides/industry"
status = 301
force = true

[[redirects]]
from = "/guides/industry/testing.html"
to = "/guides/industry/testing"
status = 301
force = true

[[redirects]]
from = "/guides/industry/overview.html"
to = "/guides/industry/overview"
status = 301
force = true

[[redirects]]
from = "/guides/industry/culture.html"
to = "/guides/industry/culture"
status = 301
force = true

[[redirects]]
from = "/guides/business/ip.html"
to = "/guides/business/ip"
status = 301
force = true

[[redirects]]
from = "/guides/business/kickstarter.html"
to = "/guides/business/kickstarter"
status = 301
force = true

[[redirects]]
from = "/guides/business/pr.html"
to = "/guides/business/pr"
status = 301
force = true

[[redirects]]
from = "/guides/business/tactics.html"
to = "/guides/business/tactics"
status = 301
force = true

[[redirects]]
from = "/guides/business/youtube.html"
to = "/guides/business/youtube"
status = 301
force = true